# Generated by Django 2.2.1 on 2019-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default='0', max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verification',
            field=models.BooleanField(blank=True),
        ),
    ]
